# Generated by Django 5.2.17 on 2026-10-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("encrypted_name", models.TextField()),
                ("wrapped_file_key", models.CharField(max_length=128)),
                ("segment_size", models.PositiveIntegerField()),
                ("segment_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("uploading", "Uploading"), ("complete", "Complete")],
                        default="uploading",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("content_id", models.CharField(db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["owner", "-created_at"], name="files_file_owner_i_2b764f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="segment",
            constraint=models.UniqueConstraint(
                fields=("file", "index"), name="unique_segment_per_file"
            ),
        ),
    ]
