# Generated by Django 5.2.17 on 2026-10-06 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Phone or email, for support and payouts.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive operators' nodes get no new copies.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Blob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.CharField(max_length=128, unique=True)),
                ("size", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "on_gateway",
                    models.BooleanField(
                        default=True,
                        help_text="The gateway still holds its staging copy.",
                    ),
                ),
                (
                    "released_from_gateway_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="No file uses it any more; copies are being dropped.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["deleted_at", "on_gateway"],
                        name="network_blo_deleted_770d25_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NodeInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("node_name", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="network.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "peer_id",
                    models.CharField(
                        help_text="The node's IPFS identity.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=200)),
                (
                    "capacity_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Space the operator set aside (Kubo StorageMax).",
                    ),
                ),
                (
                    "used_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Space IPFS reports as used."
                    ),
                ),
                ("pinned_count", models.PositiveIntegerField(default=0)),
                ("addresses", models.JSONField(blank=True, default=list)),
                ("agent_version", models.CharField(blank=True, max_length=40)),
                ("kubo_version", models.CharField(blank=True, max_length=40)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="network.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["operator__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Replica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("stored", "Stored"),
                            ("releasing", "Releasing"),
                            ("lost", "Lost"),
                        ],
                        default="assigned",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("stored_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replicas",
                        to="network.blob",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replicas",
                        to="network.node",
                    ),
                ),
            ],
            options={
                "ordering": ["blob_id", "node_id"],
                "indexes": [
                    models.Index(
                        fields=["node", "state"], name="network_rep_node_id_d2822c_idx"
                    ),
                    models.Index(
                        fields=["state", "assigned_at"],
                        name="network_rep_state_0f3fc5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blob", "node"), name="one_replica_per_node"
                    )
                ],
            },
        ),
    ]
